echo Generating API docs ...
php artisan api:generate --router="dingo" --routePrefix="v1"
echo Done ...
echo Git adding and committing
cd  ~/Desktop/Work/ido_app/wsmooth/public/docs 
git add .
git commit -m "updating documentation"
echo Done ...
echo "Pushing the changes upstream"
git push origin master
echo Done ... 
echo Enjoy thyself mortal ...

