<?php

return [

    'message' => [
        'status' => [
            'pending' => 1,
            'sent' => 2,
            'seen' => 3,
        ],
        'type' => [
            'to_group' => 1,
            'to_user' => 2,
        ],
    ],

    'info_keys' => [
        'about' => 'about',
        'terms' => 'terms',
        'policy' => 'policy',
    ],

    'admin_route_codes' => [
        'dashboard' => 1,
        'users' => 2,
        'vendors' => 3,
        'engagements' => 4,
        'weddings' => 5,
        'inspirations' => 6,
        'advertisements' => 7,
        'settings' => 8,
        'notifications' => 9,
        'reports' => 10,
    ],

    'invitation' => [
        'app'       => 1,
        'mail'      => 2,
        'phone'     => 3,
    ],

    'pages' => [
        'small'         => 15,
        'medium'        => 20,
        'huge'          => 25,
    ],

    'privacy' => [
        'private'       => 0,
        'invited'       => 1,
        'public'        => 2,
    ],

    'gender' => [
        'male'      => 'male',
        'female'    => 'female',
    ],

    'culture' => [
        'christian'         => 0,
        'hindu'             => 1,
        'muslim'            => 2,
        'traditional'       => 3,
    ],

    'engagement' => [
        'status' => [
            'pending' => 0,
            'rejected' => 1,
            'accepted' => 2,
        ],
    ],

    'errors' => [
        'success' => 0,
        'internal_error' => 1,
        'user' => [
            'invalid_login' => 100,
            'not_found' => 101,    
            'created_with_fb' => 102, 
            'email_not_verified' => 103,
            'fb_id_not_found' => 104,
        ],
    ],

    'error' => [
        'success'                           => 0,
        'invalid_login'                     => 1,
        'internal_error'                    => 2,
        'user_not_found'                    => 3,
        'wrong_old_password'                => 4,
        'token_expired'                     => 5,
        'token_invalid'                     => 6,
        'not_found'                         => 7,
        'unauthorized_access'               => 8,
        'unauthorized_creation'             => 9,
        'already_created'                   => 10,
        'account_created_with_fb'           => 11,
    ],

    'validation' => [
        'codes' => [
            'not_accepted'                  => '1000',
            'not_url'                       => '1001',
            'not_date'                      => '1002',
            'not_letters'                   => '1003',
            'not_letters_numbers_dashes'    => '1004',
            'not_numeric'                   => '1005',
            'not_array'                     => '1006',
            'not_before_date'               => '1007',
            'not_before_or_equal_date'      => '1008',
            'not_between_numeric'           => '1009',
            'not_between_kilobytes'         => '1010',
            'not_between_length'            => '1011',
            'not_between_items_count'       => '1012',
            'not_boolean'                   => '1013',
            'not_confirmed'                 => '1014',
            'not_speficied_format'          => '1016',
            'not_different_from_other'      => '1017',
            'not_digits'                    => '1018',
            'not_digits_between'            => '1019',
            'not_valid_dimensions'          => '1020',
            'has_duplicate'                 => '1021',
            'not_email'                     => '1022',
            'not_after_or_equal_date'       => '1023',
            'not_file'                      => '1024',
            'not_nullable'                  => '1025',
            'not_image'                     => '1026',
            'exist_in_specified'            => '1028',
            'not_integer'                   => '1029',
            'not_valid'                     => '1030',
            'not_ip'                        => '1031',
            'not_json'                      => '1032',
            'greater_value'                 => '1033',
            'greater_kilobytes'             => '1034',
            'greater_length'                => '1035',
            'greater_count'                 => '1036',
            'not_file_type'                 => '1037',
            'not_file_types'                => '1038',
            'lesser_value'                  => '1039',
            'lesser_kilobytes'              => '1040',
            'lesser_length'                 => '1041',
            'lesser_count'                  => '1042',
            'not_after_date'                => '1043',
            'not_present'                   => '1045',
            'required'                      => '1047',
            'required_if_specified'         => '1048',
            'required_unless_specified'     => '1049',
            'required_when_specified'       => '1050',
            'required_when_all_specified'   => '1051',
            'required_when_not_specified'   => '1052',
            'required_when_all_not_specified' => '1053',
            'not_match_specified'           => '1054',
            'not_numeric_size'              => '1055',
            'not_kilobytes_size'            => '1056',
            'not_length_size'               => '1057',
            'not_array_size'                => '1058',
            'not_string'                    => '1059',
            'not_timezone'                  => '1060',
            'not_unique'                    => '1061',
            'upload_failed'                 => '1062',
        ],

        'messages' => [
            '1000' => ' has not been accepted',
            '1001' => ' is not a valid url',
            '1002' => ' is not a valid date',
            '1003' => ' should be letters only',
            '1004' => ' should be letters, numbers or dashes only',
            '1005' => ' is not numeric',
            '1006' => ' is not an array',
            '1007' => ' date should be before the specified date',
            '1008' => ' should be before or equal the specified date',
            '1009' => ' should be between the specified value',
            '1010' => ' should be between the specified size in kilobytes',
            '1011' => ' should be between the specified size in characters',
            '1012' => ' array should have the specified size',
            '1013' => ' should be boolean',
            '1014' => ' should have a {this_field}_confirmation field',
            '1016' => ' should be of the specified format',
            '1017' => ' should not be different from the other specified field',
            '1018' => ' should be digits',
            '1019' => ' digits should be between specified size',
            '1020' => ' is not valid dimension',
            '1021' => ' has a duplicate value',
            '1022' => ' given is not a valid email',
            '1023' => ' is not equal or after the specified date',
            '1024' => ' is not a valid ',
            '1025' => ' should not be empty',
            '1026' => ' is not an image',
            '1028' => ' is not valid as specified',
            '1029' => ' is not an integer',
            '1030' => ' is not valid',
            '1031' => ' is not a valid ip address',
            '1032' => ' is not json',
            '1033' => ' is greater than value specified',
            '1034' => ' is greater in kilobytes than specified',
            '1035' => ' is greater in length than specified',
            '1036' => ' has more items than specified',
            '1037' => ' is not a file type specified',
            '1038' => ' is not of file types required',
            '1039' => ' is of lesser value than specified',
            '1040' => ' is of lesser size in kilobytes than specified',
            '1041' => ' is of lesser length than specified',
            '1042' => ' is of fewer items than required',
            '1043' => ' is not after date specified',
            '1045' => ' is not present',
            '1047' => ' is required',
            '1048' => ' is required if other fields are as specified',
            '1049' => ' is required unless other fields are as specified',
            '1050' => ' is required when the other field is as specified',
            '1051' => ' is required when all the other fields are as specified',
            '1052' => ' is required when the other fields is not as specified',
            '1053' => ' is required when all the other fields are as specified',
            '1054' => ' does not match the other field as specified',
            '1055' => ' is note numeric size specified',
            '1056' => ' is not the specified size in kilobytes',
            '1057' => ' is not the specified length',
            '1058' => ' is not array size specified',
            '1059' => ' is not a string',
            '1060' => ' is not a timezone',
            '1061' => ' is not unique',
            '1062' => ' upload failed',
        ],
    ],

];
